environment: "local"
storage_type: mock

server:
  port: ":2131"
  host: "localhost"

file:
  maxSize: 209715200 # 200MB
  allowedTypes:
    - "image/jpeg"
    - "image/png"
    - "application/pdf"
  path: "./tempFiles"
  timeout: 30
  unit: "s"
  chunkSize: 1048576 # 1MB

logging:
  level: "info"

database:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  dbname: "file_uploader"

aws:
  region: "ap-southeast-2"
  s3:
    bucket_name: file-uploader-uploads-330154525676
    presigned_url_expiry: 30 # in minutes

otel:
  enabled: true
  exporter:
    type: "otlp"
    endpoint: "localhost:4318"
    insecure: true
  service_name: "file-uploader-service"
  resource_attributes:
    - "service.name=file-uploader-service"
    - "service.version=1.0.0"
    - "service.instance.id=instance-12345"