server:
  port: ":8080"
  host: "localhost"

file:
  maxSize: 209715200 # 200MB
  path: "./tempFiles"
  timeout: 30
  unit: "s"
  chunkSize: 1048576 # 1MB

logging:
  level: "info"

database:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  dbname: "file_uploader"

aws:
  region: "ap-southeast-2"
  s3:
    bucket_name: file-uploader-uploads-330154525676
    presigned_url_expiry: 30 # in minutes
