version: '3.8'

services:
  file-uploader-go-service:
    build: .
    ports:
      - "2131:2131"

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html
    depends_on:
      - file-uploader