version: '3.8'

services:
  go-service:
    build: .
    ports:
      - "2131:2131"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html
    depends_on:
      - go-service

  integration-tests:
    build:
      context: .
      target: builder
    working_dir: /app
    entrypoint: go test -v ./cmd/integration_test.go ./cmd/main.go
    depends_on:
      - go-service
      - nginx