name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run tests
        run: go test -v ./...

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run integration tests
        run: docker-compose up --build --abort-on-container-exit integration-tests -count=1
      
      - name: Build the Docker image
        run: docker build . --file dockerfile --tag my-image-name:$(date +%s)